version: "3.7"

services:
  web:
    image: nodered/node-red:3.1.3
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      PORT: 31881
      TZ: Asia/Tokyo
    network_mode: host
